### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by brenard** [kamaradclimber/rte-ecowatt#11]
Après la mise à jour en version _0.2.1_, j'ai tenté la reconfiguration en utilisant l'interface et j'ai cette erreur dans les logs d'Home Assistant :

```
Oct 05 22:52:20 skinner hass[15374]: 2022-10-05 22:52:20.431 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.rte_ecowatt.config_flow
Oct 05 22:52:20 skinner hass[15374]: Traceback (most recent call last):
Oct 05 22:52:20 skinner hass[15374]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 722, in get_platform
Oct 05 22:52:20 skinner hass[15374]:     cache[full_name] = self._import_platform(platform_name)
Oct 05 22:52:20 skinner hass[15374]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 739, in _import_platform
Oct 05 22:52:20 skinner hass[15374]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Oct 05 22:52:20 skinner hass[15374]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Oct 05 22:52:20 skinner hass[15374]:     return _bootstrap._gcd_import(name[level:], package, level)
Oct 05 22:52:20 skinner hass[15374]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Oct 05 22:52:20 skinner hass[15374]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Oct 05 22:52:20 skinner hass[15374]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Oct 05 22:52:20 skinner hass[15374]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Oct 05 22:52:20 skinner hass[15374]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Oct 05 22:52:20 skinner hass[15374]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Oct 05 22:52:20 skinner hass[15374]:   File "/srv/homeassistant/.homeassistant/custom_components/rte_ecowatt/config_flow.py", line 29, in <module>
Oct 05 22:52:20 skinner hass[15374]:     class SetupConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
Oct 05 22:52:20 skinner hass[15374]:   File "/srv/homeassistant/.homeassistant/custom_components/rte_ecowatt/config_flow.py", line 30, in SetupConfigFlow
Oct 05 22:52:20 skinner hass[15374]:     async def async_step_user(self, user_input: dict[str, Any] | None = None):
Oct 05 22:52:20 skinner hass[15374]: TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
Oct 05 22:52:20 skinner hass[15374]: 2022-10-05 22:52:20.436 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration rte_ecowatt: Exception importing custom_components.rte_ecowatt.config_flow
```

Ça ressemble à un problème de compatibilité entre versions de python, donc je précise que je suis en python _3.9.2_. J'ai corrigé le problème en supprimant le typage du paramètre _user_input_ des méthodes de la classe _SetupConfigFlow_ et j'ai pu finaliser la configuration de l'intégration via l'interface.

**Comment by kamaradclimber** [comment]
En effet, le code utilise https://peps.python.org/pep-0604/ qui est apparu en python 3.10. On remplace facilement cette syntaxe par l'usage d'`Optional`.

**Comment by brenard** [comment]
Je sais pas si c'est un oubli et que cela a été introduit par un commit suivant, mais il reste un cas à corriger ligne 140 :

```
Nov 03 11:44:02 skinner hass[21075]: 2022-11-03 11:44:02.741 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.rte_ecowatt.config_flow
Nov 03 11:44:02 skinner hass[21075]: Traceback (most recent call last):
Nov 03 11:44:02 skinner hass[21075]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
Nov 03 11:44:02 skinner hass[21075]:     cache[full_name] = self._import_platform(platform_name)
Nov 03 11:44:02 skinner hass[21075]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
Nov 03 11:44:02 skinner hass[21075]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Nov 03 11:44:02 skinner hass[21075]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Nov 03 11:44:02 skinner hass[21075]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 03 11:44:02 skinner hass[21075]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Nov 03 11:44:02 skinner hass[21075]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Nov 03 11:44:02 skinner hass[21075]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Nov 03 11:44:02 skinner hass[21075]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Nov 03 11:44:02 skinner hass[21075]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Nov 03 11:44:02 skinner hass[21075]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Nov 03 11:44:02 skinner hass[21075]:   File "/srv/homeassistant/.homeassistant/custom_components/rte_ecowatt/config_flow.py", line 133, in <module>
Nov 03 11:44:02 skinner hass[21075]:     class OptionsFlowHandler(config_entries.OptionsFlow):
Nov 03 11:44:02 skinner hass[21075]:   File "/srv/homeassistant/.homeassistant/custom_components/rte_ecowatt/config_flow.py", line 140, in OptionsFlowHandler
Nov 03 11:44:02 skinner hass[21075]:     self, user_input: dict[str, Any] | None = None
Nov 03 11:44:02 skinner hass[21075]: TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
Nov 03 11:44:02 skinner hass[21075]: 2022-11-03 11:44:02.754 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration rte_ecowatt to set up rte_ecowatt configuration entry: Exception importing custom_components.rte_ecowatt.config_flow
```

**Comment by kamaradclimber** [comment]
Bien vu, merci d'avoir rapporté le problème. Je corrige ca tout de suite.

**Comment by brenard** [comment]
Cette fois-ci je confirme, ça fonctionne parfaitement en python 3.8. Merci pour la correction et pour cette intégration bien utile !

**Comment by brenard** [comment]
Même erreur, le retour :)

https://github.com/kamaradclimber/rte-ecowatt/blob/main/custom_components/rte_ecowatt/__init__.py#L245
https://github.com/kamaradclimber/rte-ecowatt/blob/main/custom_components/rte_ecowatt/__init__.py#L650

PS : la fin du support de python 3.9 est annoncé pour la version _2023.2_, mais en attendant ... :) De mon côté, j'ai toujours pas trouvé de backports pour Debian Bullseye de python 3.10.

**Comment by kamaradclimber** [comment]
Merci du report. Ca sera fixé dans la prochaine release.
Ce qui est bizarre est qu'on trouve ce genre de construction dans le code d'HA :thinking:

**Comment by kamaradclimber** [comment]
La version 0.6.4 devrait refixer le problème.

**Comment by brenard** [comment]
> La version 0.6.4 devrait refixer le problème.

Je confirme, plus d'erreur. Merci !
