### ISSUE TITLE
No sensor are created with graphical integration

### ISSUE THREAD

**Issue by Ano10** [kamaradclimber/rte-ecowatt#12]
Here is what I did.
I've removed previous HACS repo, removed rte-ecowatt config from yaml, deleted according sensors and reboot.
I've clicked on installation button from github site, selected beta 0.2.1 and installed it (no info for rebooting at end of installation, I don't know if it's normal), then rebooted.
I've added new integration, choosed rte-ecowatt, filled my credential, choosed "default sensors" and validated but no sensor were created.

Here is the error from log
`Logger: homeassistant.components.sensor
Source: custom_components/rte_ecowatt/sensor.py:61
Integration: Capteur (documentation, issues)
First occurred: 07:58:57 (1 occurrences)
Last logged: 07:58:57

Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 61, in async_setup_entry
    for sensor_config in entry.data["sensors"]:
KeyError: 'sensors'
`

**Comment by freefloris** [comment]
Bonjour,

Même problème pour moi.

J'ai contourné en ciblant la version "main" plutôt qu'un numéro.

A noter que toutes les sondes renvoient "inconnu" depuis hier soir.
Mais je n'ai pas beaucoup dormi, je verrais ça ce soir :-)

Cordialement.

**Comment by kamaradclimber** [comment]
Le problème apparaissait lorsqu'on ne définit pas de capteur custom. Le problème sera fixé dans la prochaine release.
Je suis étonné delire que la version main fonctionnait cependant.
