### ISSUE TITLE
Error while setting up rte_ecowatt platform for sensor

### ISSUE THREAD

**Issue by lahayeg** [kamaradclimber/rte-ecowatt#2]
Bonjour

Premiere installation sur Home Assistant 2022.9.5

```- platform: rte_ecowatt
  api_client_id: xx
  api_client_secret: xx
  sensors:
    - unit: days
      shift: 2
```

```2022-09-21 09:49:38.193 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
File "/config/custom_components/rte_ecowatt/sensor.py", line 141, in update_method
api_result = await client.get(url, headers=headers)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/rte_ecowatt/sensor.py", line 166, in update_method
raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Server disconnected
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/rte_ecowatt/sensor.py", line 99, in async_setup_platform
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: Server disconnected```

**Comment by kamaradclimber** [comment]
Hello, merci d'avoir pris le temps de rapporter le problème.

Est-ce que la communication fonctionne à nouveau après 15 minutes? Ou après un redémarrage d'HomeAssistant? Ou bien est-ce que l'erreur se reproduit systématiquement?

Le message `Server disconnected` semble très générique et semble indiquer un problème de communication avec l'API de RTE.

**Comment by Ano10** [comment]
Le site a effectué une maintenance, c'est peut-être lié ?
"Le 21 septembre 2022, une maintenance planifiée rendra indisponible l’accès aux API SPEED entre 08:00 et 10:00. Pour tout renseignement complémentaire merci de contacter rte-hotline@rte-france.com "

**Comment by lahayeg** [comment]
@kamaradclimber apres HA restart, fixed!
Merci
