### ISSUE TITLE
Error communicating with RTE API: requests too frequent to RTE API

### ISSUE THREAD

**Issue by marc-cizeron** [kamaradclimber/rte-ecowatt#3]
Salut, 

Après configuration qui se passe bien, je récupère les valeurs ça fonctionne, c'est nickel !

Par contre au bout de quelque minutes j'ai droits à cette erreur :

```
Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:178
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:28:37 (1 occurrences)
Last logged: 10:28:37

Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/sensor.py", line 146, in update_method
    raise UpdateFailed(
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with RTE API: requests too frequent to RTE API

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rte_ecowatt/sensor.py", line 166, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Error communicating with RTE API: requests too frequent to RTE API

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 99, in async_setup_platform
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: Error communicating with RTE API: requests too frequent to RTE API
```

J'ai regarder sur data.rte-france.com sur mon app si il y avait des quotas d'appelle API. J'ai rien trouvé.

Super taff byw, dispo pour test plus d'infos.

**Comment by kamaradclimber** [comment]
Hello,

l'API impose un appel maximum par tranche de 15 minutes. Cette erreur est attendue après un redémarrage d'home-assistant.
C'est un bug dans le sens où l'intégration devrait être capable de reprendre les valeurs obtenues avant le redémarrage afin d'éviter un appel à l'API. Il faut que je travaille dessus.

**Comment by marc-cizeron** [comment]
Merci pour les précisions. C'est vrai que j'ai fait plusieurs redémarrage ce matin. Sauf qu'il me semble avoir déjà eu l'erreur sans forcément faire de redémarrage.

J'observe comment ça se passe, je reviens si j'ai des précisions.
