### ISSUE TITLE
Unable to find ecowatt level dans le futur

### ISSUE THREAD

**Issue by kamaradclimber** [kamaradclimber/rte-ecowatt#30]
Salut et merci pour vos efforts.

Tout marche pas mal jusqu’à ce que je choisisse une entité "Jour + x heures"

`2022-12-05 21:08:30.001 DEBUG (MainThread) [custom_components.rte_ecowatt] Calling update method, 5 listeners subscribed
2022-12-05 21:08:30.001 DEBUG (MainThread) [custom_components.rte_ecowatt] Starting collecting data
2022-12-05 21:08:30.279 DEBUG (MainThread) [custom_components.rte_ecowatt] Fetched a token for RTE API
2022-12-05 21:08:30.377 INFO (MainThread) [custom_components.rte_ecowatt] data received, status code: 200
2022-12-05 21:08:30.377 DEBUG (MainThread) [custom_components.rte_ecowatt] api response body: {"signals":[{"GenerationFichier":"2022-12-04T23:00:00+01:00","jour":"2022-12-05T00:00:00+01:00","dvalue":1,"message":"Pas d\u2019alerte.","values":[{"pas":0,"hvalue":1},{"pas":1,"hvalue":1},{"pas":2,"hvalue":1},{"pas":3,"hvalue":1},{"pas":4,"hvalue":1},{"pas":5,"hvalue":1},{"pas":6,"hvalue":1},{"pas":7,"hvalue":1},{"pas":8,"hvalue":1},{"pas":9,"hvalue":1},{"pas":10,"hvalue":1},{"pas":11,"hvalue":1},{"pas":12,"hvalue":1},{"pas":13,"hvalue":1},{"pas":14,"hvalue":1},{"pas":15,"hvalue":1},{"pas":16,"hvalue":1},{"pas":17,"hvalue":1},{"pas":18,"hvalue":1},{"pas":19,"hvalue":1},{"pas":20,"hvalue":1},{"pas":21,"hvalue":1},{"pas":22,"hvalue":1},{"pas":23,"hvalue":1}]},{"GenerationFichier":"2022-12-04T23:00:00+01:00","jour":"2022-12-06T00:00:00+01:00","dvalue":1,"message":"Pas d\u2019alerte.","values":[{"pas":0,"hvalue":1},{"pas":1,"hvalue":1},{"pas":2,"hvalue":1},{"pas":3,"hvalue":1},{"pas":4,"hvalue":1},{"pas":5,"hvalue":1},{"pas":6,"hvalue":1},{"pas":7,"hvalue":1},{"pas":8,"hvalue":1},{"pas":9,"hvalue":1},{"pas":10,"hvalue":1},{"pas":11,"hvalue":1},{"pas":12,"hvalue":1},{"pas":13,"hvalue":1},{"pas":14,"hvalue":1},{"pas":15,"hvalue":1},{"pas":16,"hvalue":1},{"pas":17,"hvalue":1},{"pas":18,"hvalue":1},{"pas":19,"hvalue":1},{"pas":20,"hvalue":1},{"pas":21,"hvalue":1},{"pas":22,"hvalue":1},{"pas":23,"hvalue":1}]},{"GenerationFichier":"2022-12-04T23:00:00+01:00","jour":"2022-12-07T00:00:00+01:00","dvalue":1,"message":"Pas d\u2019alerte.","values":[{"pas":0,"hvalue":1},{"pas":1,"hvalue":1},{"pas":2,"hvalue":1},{"pas":3,"hvalue":1},{"pas":4,"hvalue":1},{"pas":5,"hvalue":1},{"pas":6,"hvalue":1},{"pas":7,"hvalue":1},{"pas":8,"hvalue":1},{"pas":9,"hvalue":1},{"pas":10,"hvalue":1},{"pas":11,"hvalue":1},{"pas":12,"hvalue":1},{"pas":13,"hvalue":1},{"pas":14,"hvalue":1},{"pas":15,"hvalue":1},{"pas":16,"hvalue":1},{"pas":17,"hvalue":1},{"pas":18,"hvalue":1},{"pas":19,"hvalue":1},{"pas":20,"hvalue":1},{"pas":21,"hvalue":1},{"pas":22,"hvalue":1},{"pas":23,"hvalue":1}]},{"GenerationFichier":"2022-12-04T23:00:00+01:00","jour":"2022-12-08T00:00:00+01:00","dvalue":1,"message":"Pas d\u2019alerte.","values":[{"pas":0,"hvalue":1},{"pas":1,"hvalue":1},{"pas":2,"hvalue":1},{"pas":3,"hvalue":1},{"pas":4,"hvalue":1},{"pas":5,"hvalue":1},{"pas":6,"hvalue":1},{"pas":7,"hvalue":1},{"pas":8,"hvalue":1},{"pas":9,"hvalue":1},{"pas":10,"hvalue":1},{"pas":11,"hvalue":1},{"pas":12,"hvalue":1},{"pas":13,"hvalue":1},{"pas":14,"hvalue":1},{"pas":15,"hvalue":1},{"pas":16,"hvalue":1},{"pas":17,"hvalue":1},{"pas":18,"hvalue":1},{"pas":19,"hvalue":1},{"pas":20,"hvalue":1},{"pas":21,"hvalue":1},{"pas":22,"hvalue":1},{"pas":23,"hvalue":1}]}]}
2022-12-05 21:08:30.379 DEBUG (MainThread) [custom_components.rte_ecowatt] data parsed: [{'GenerationFichier': '2022-12-04T23:00:00+01:00', 'jour': '2022-12-05T00:00:00+01:00', 'dvalue': 1, 'message': 'Pas d’alerte.', 'values': [{'pas': 0, 'hvalue': 1}, {'pas': 1, 'hvalue': 1}, {'pas': 2, 'hvalue': 1}, {'pas': 3, 'hvalue': 1}, {'pas': 4, 'hvalue': 1}, {'pas': 5, 'hvalue': 1}, {'pas': 6, 'hvalue': 1}, {'pas': 7, 'hvalue': 1}, {'pas': 8, 'hvalue': 1}, {'pas': 9, 'hvalue': 1}, {'pas': 10, 'hvalue': 1}, {'pas': 11, 'hvalue': 1}, {'pas': 12, 'hvalue': 1}, {'pas': 13, 'hvalue': 1}, {'pas': 14, 'hvalue': 1}, {'pas': 15, 'hvalue': 1}, {'pas': 16, 'hvalue': 1}, {'pas': 17, 'hvalue': 1}, {'pas': 18, 'hvalue': 1}, {'pas': 19, 'hvalue': 1}, {'pas': 20, 'hvalue': 1}, {'pas': 21, 'hvalue': 1}, {'pas': 22, 'hvalue': 1}, {'pas': 23, 'hvalue': 1}], 'date': datetime.date(2022, 12, 5)}, {'GenerationFichier': '2022-12-04T23:00:00+01:00', 'jour': '2022-12-06T00:00:00+01:00', 'dvalue': 1, 'message': 'Pas d’alerte.', 'values': [{'pas': 0, 'hvalue': 1}, {'pas': 1, 'hvalue': 1}, {'pas': 2, 'hvalue': 1}, {'pas': 3, 'hvalue': 1}, {'pas': 4, 'hvalue': 1}, {'pas': 5, 'hvalue': 1}, {'pas': 6, 'hvalue': 1}, {'pas': 7, 'hvalue': 1}, {'pas': 8, 'hvalue': 1}, {'pas': 9, 'hvalue': 1}, {'pas': 10, 'hvalue': 1}, {'pas': 11, 'hvalue': 1}, {'pas': 12, 'hvalue': 1}, {'pas': 13, 'hvalue': 1}, {'pas': 14, 'hvalue': 1}, {'pas': 15, 'hvalue': 1}, {'pas': 16, 'hvalue': 1}, {'pas': 17, 'hvalue': 1}, {'pas': 18, 'hvalue': 1}, {'pas': 19, 'hvalue': 1}, {'pas': 20, 'hvalue': 1}, {'pas': 21, 'hvalue': 1}, {'pas': 22, 'hvalue': 1}, {'pas': 23, 'hvalue': 1}], 'date': datetime.date(2022, 12, 6)}, {'GenerationFichier': '2022-12-04T23:00:00+01:00', 'jour': '2022-12-07T00:00:00+01:00', 'dvalue': 1, 'message': 'Pas d’alerte.', 'values': [{'pas': 0, 'hvalue': 1}, {'pas': 1, 'hvalue': 1}, {'pas': 2, 'hvalue': 1}, {'pas': 3, 'hvalue': 1}, {'pas': 4, 'hvalue': 1}, {'pas': 5, 'hvalue': 1}, {'pas': 6, 'hvalue': 1}, {'pas': 7, 'hvalue': 1}, {'pas': 8, 'hvalue': 1}, {'pas': 9, 'hvalue': 1}, {'pas': 10, 'hvalue': 1}, {'pas': 11, 'hvalue': 1}, {'pas': 12, 'hvalue': 1}, {'pas': 13, 'hvalue': 1}, {'pas': 14, 'hvalue': 1}, {'pas': 15, 'hvalue': 1}, {'pas': 16, 'hvalue': 1}, {'pas': 17, 'hvalue': 1}, {'pas': 18, 'hvalue': 1}, {'pas': 19, 'hvalue': 1}, {'pas': 20, 'hvalue': 1}, {'pas': 21, 'hvalue': 1}, {'pas': 22, 'hvalue': 1}, {'pas': 23, 'hvalue': 1}], 'date': datetime.date(2022, 12, 7)}, {'GenerationFichier': '2022-12-04T23:00:00+01:00', 'jour': '2022-12-08T00:00:00+01:00', 'dvalue': 1, 'message': 'Pas d’alerte.', 'values': [{'pas': 0, 'hvalue': 1}, {'pas': 1, 'hvalue': 1}, {'pas': 2, 'hvalue': 1}, {'pas': 3, 'hvalue': 1}, {'pas': 4, 'hvalue': 1}, {'pas': 5, 'hvalue': 1}, {'pas': 6, 'hvalue': 1}, {'pas': 7, 'hvalue': 1}, {'pas': 8, 'hvalue': 1}, {'pas': 9, 'hvalue': 1}, {'pas': 10, 'hvalue': 1}, {'pas': 11, 'hvalue': 1}, {'pas': 12, 'hvalue': 1}, {'pas': 13, 'hvalue': 1}, {'pas': 14, 'hvalue': 1}, {'pas': 15, 'hvalue': 1}, {'pas': 16, 'hvalue': 1}, {'pas': 17, 'hvalue': 1}, {'pas': 18, 'hvalue': 1}, {'pas': 19, 'hvalue': 1}, {'pas': 20, 'hvalue': 1}, {'pas': 21, 'hvalue': 1}, {'pas': 22, 'hvalue': 1}, {'pas': 23, 'hvalue': 1}], 'date': datetime.date(2022, 12, 8)}]
2022-12-05 21:08:30.379 INFO (MainThread) [custom_components.rte_ecowatt] Fetching ecowatt api data recovered
2022-12-05 21:08:30.379 DEBUG (MainThread) [custom_components.rte_ecowatt] Finished fetching ecowatt api data in 0.378 seconds (success: True)
2022-12-05 21:08:30.379 DEBUG (MainThread) [custom_components.rte_ecowatt] Looking for 2022-12-05 21:08:30.379825+01:00
2022-12-05 21:08:30.380 INFO (MainThread) [custom_components.rte_ecowatt] updated 'Next downgraded period'
2022-12-05 21:08:30.380 DEBUG (MainThread) [custom_components.rte_ecowatt] Looking for 2022-12-09 19:08:30.380546+01:00
2022-12-05 21:08:30.380 INFO (MainThread) [custom_components.rte_ecowatt] Data for relevant day: None
2022-12-05 21:08:30.380 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 392, in _find_ecowatt_level
    ecowatt_data = next(
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 325, in _handle_coordinator_update
    ecowatt_level = self._find_ecowatt_level()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 416, in _find_ecowatt_level
    raise RuntimeError(
RuntimeError: Unable to find ecowatt level for 2022-12-09 19:08:30.380546+01:00 (hour shift: 22)`

A noter que le `(hour shift: 22)` change suivant le nombre d'heure que je demande.
Si je peux vous être utile...

_Originally posted by @michelsup in https://github.com/kamaradclimber/rte-ecowatt/issues/28#issuecomment-1338105949_

**Comment by kamaradclimber** [comment]
@michelsup, merci du rapport. Le problème semble indépendant de #28 , j'ai donce déplacé le commentaire dans un nouveau bug.

**Comment by kamaradclimber** [comment]
Il me semble que le "jour + x heures" doit être assez élevé puisque ca fait référence à "2022-12-09 19:08:30.380546+01:00" (c'est à dire dans un peu moins de  4 jours). Je pense que l'API de RTE n'expose pas aussi loin.
Qu'avez vous rentré comme nombre d'heure en avance?

**Comment by michelsup** [comment]
> Qu'avez vous rentré comme nombre d'heure en avance?

On va se tutoyer :)

J'ai rentré le max, 95H. Mais avec moins c'est pareil, ca plante toujours. J'avoue ne pas avoir tenté sur une durée inférieure à 24h. Mais avec cette punaise de limitation c'est assez long pour debugger.

**Comment by kamaradclimber** [comment]
J'ai corrigé l'amplitude de configuration des capteurs pour coller à ce qui semble guaranti.
