### ISSUE TITLE
erreur apres mise à jour 6.3

### ISSUE THREAD

**Issue by HaarNhoo** [kamaradclimber/rte-ecowatt#46]
Bonjour @kamaradclimber

Après la mise à jour de 0.4.2 en 0.6.3.  l'intégration à planté, j'ai le message :  Le flux de configuration n'a pas pu être chargé: {"message":"Invalid handler specified"}  qui s'affiche lors du clic sur l'intégration.
Et ce même après désinstallation / réinstallation complète dans HACS. (avec bien sûr des redémarrages à chaque étapes)

Une idée de ce qui pourrait clocher ?

```
 Logger: homeassistant.config_entries
Source: config_entries.py:810
First occurred: 13:45:47 (2 occurrences)
Last logged: 13:49:32
Error occurred loading configuration flow for integration rte_ecowatt: Exception importing custom_components.rte_ecowatt.config_flow
```

```
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.loader
Source: custom_components/rte_ecowatt/__init__.py:245
Integration: rte_ecowatt (documentation, issues)
First occurred: 13:45:46 (2 occurrences)
Last logged: 13:49:32

Unexpected exception importing platform custom_components.rte_ecowatt.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/rte_ecowatt/__init__.py", line 237, in <module>
    class DowngradedEcowattLevelCalendar(CoordinatorEntity, CalendarEntity):
  File "/home/homeassistant/.homeassistant/custom_components/rte_ecowatt/__init__.py", line 245, in DowngradedEcowattLevelCalendar
    def event(self) -> CalendarEvent | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by kamaradclimber** [comment]
Bonjour,
ce problème a été remonté dans #11, cela vient de l'utilisation de python 3.9 qui ne supporte certaines syntaxes du langage.

https://github.com/kamaradclimber/rte-ecowatt/issues/11#issuecomment-1353035724
