### ISSUE TITLE
Erreur avec l'intégration 0.6.5

### ISSUE THREAD

**Issue by Yoanf26** [kamaradclimber/rte-ecowatt#49]
J'ai un problème avec cette API à jour depuis mon HA à jour.

J'ai cette erreur dans les journaux.

```
Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:197
Integration: Capteur (documentation, issues)
First occurred: 15:34:28 (2 occurrences)
Last logged: 15:35:22

Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 595, in update_method
    shedding_event["start_date"] = self._parse_enedis_time(
  File "/config/custom_components/rte_ecowatt/__init__.py", line 610, in _parse_enedis_time
    a = datetime.strptime(time_string, "%d/%m/%Y %H:%M")
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: :00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 607, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: unconverted data remains: :00

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 92, in async_setup_entry
    await enedis_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 197, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: unconverted data remains: :00
```

J'ai tenté la suppression, redémarrage de HA, ajout de l'intégration avec mon ID Client et mon ID Secret, redémarrage HA.

**Comment by kamaradclimber** [comment]
Le problème vient certainement du parsing des dates envoyées par l'api d'Enedis (que je n'ai jamais pu tester car aucun délestage n'est prévu pour le moment).

Pourrais tu m'envoyer des coordonnées GPS (approximatives ou une adresse) pour que je puisse reproduire et corriger le problème?

Peux tu également confirmer que https://coupures-temporaires.enedis.fr/ affiche bien des délestages pour ton adresse?

**Comment by Yoanf26** [comment]
Voici les coordonnées GPS

**Comment by kamaradclimber** [comment]
Voilà l'info remontée par l'API d'Endis:
```
{'shedding': [{'acr_date': 'lyn_20221210', 'refresh_date': '09/12/2022 11:34', 'stop_date': '10/12/2022 10:00:00', 'start_date': '10/12/2022 08:00:00'}], 'eld': False, 'success': True}
```
Je vais publier un patch, merci!

Visiblement la page web d'Enedis a été modifée depuis ma dernière visite car elle ne demande même plus l'adresse et affiche directement "Pas de délestage annoncé".

Plusieurs hypothèses:
- Enedis réalise en ce moment des tests et ne veut pas alerter les gens (tout en guardant l'API disponible)
- le format de l'API est en train de changer (et dans ce cas l'intégration devra être retravaillée).

**Comment by kamaradclimber** [comment]
![image](https://user-images.githubusercontent.com/503537/207924678-380965eb-5563-4cbe-b1d1-7c61c0226e26.png)

:partying_face:

**Comment by kamaradclimber** [comment]
Ca devrait être bon en https://github.com/kamaradclimber/rte-ecowatt/releases/tag/0.6.6

**Comment by Yoanf26** [comment]
Je confirme que c'est corrigé

**Comment by Yoanf26** [comment]
Oups, mea culpa, j'ai oublié de te remercier. Et surtout merci pour ta rapidité. Et désolé de mon oubli.
