### ISSUE TITLE
TypeError: object StoredState can't be used in 'await' expression i

### ISSUE THREAD

**Issue by kalon33** [kamaradclimber/rte-ecowatt#61]
Bonjour, avec la dernière version de l'image Docker de homeassistant, utilisant python 3.11, j'ai cette erreur dans les logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 849, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 421, in async_added_to_hass
    await super().async_added_to_hass()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 220, in async_added_to_hass
    if (last_stored_state := await self._async_get_restored_data()) is not None:
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object StoredState can't be used in 'await' expression
```

Comment la corriger?

Merci d'avance, et merci pour votre intégration bien pratique !

**Comment by kamaradclimber** [comment]
Bonjour,

je peux reproduire le problème, je regarde ca. Merci d'avoir rapporté la stacktrace!

**Comment by kalon33** [comment]
Pas de problème, merci pour le correctif !
