### ISSUE TITLE
Often no connection, breaking logic

### ISSUE THREAD

**Issue by vingerha** [kamaradclimber/rte-ecowatt#63]
Quite often (almost daily) the connection fails and this break my logic, the sensor state becomes no long erSiutaion Normale but unknown and I cannot run automations/conditions against that ..i.e. there are too many state-options if I want an alert that differs from "Situation Normale"
As the connection can probably not be resolved wihtout kicking Enedis, please consider error catching and default state
```
Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 560, in update_method
    raise UpdateFailed("Failed fetching enedis data at step 1")
homeassistant.helpers.update_coordinator.UpdateFailed: Failed fetching enedis data at step 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 609, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Failed fetching enedis data at step 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 92, in async_setup_entry
    await enedis_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: Failed fetching enedis data at step 1

**Comment by kamaradclimber** [comment]
Hello,

Enedis API stopped working a few months ago. I kept the logic there for the time being if they eventually put it back. But on the meantime, I would advise against building automation on this.
