### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by titof2375** [kamaradclimber/rte-ecowatt#64]
Salut j'ai cette erreur la 
Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:258
Integration: Capteur (documentation, issues)
First occurred: 20:14:02 (1 occurrences)
Last logged: 20:14:02

Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 187, in update_method
    raise UpdateFailed(
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with RTE API: requests too frequent to RTE API

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 206, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Error communicating with RTE API: requests too frequent to RTE API

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 98, in async_setup_entry
    await rte_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: Error communicating with RTE API: requests too frequent to RTE API

**Comment by kamaradclimber** [comment]
Bonjour,

cette erreur est attendue lorsque HA redémarre peu de temps avoir fait un rafraichissement des données de l’API.
Elle ne devrait pas arriver de façon régulière une fois HA démarré (1 fois au démarrage et ensuite plus du tout).

Je ferme le ticket mais peut le réouvrir si nécessaire bien sûr.
