### ISSUE TITLE
pas de data  Error communicating with API: Error communicating with RTE API: requests too frequent to RTE API

### ISSUE THREAD

**Issue by dcyou** [kamaradclimber/rte-ecowatt#65]
![image](https://github.com/kamaradclimber/rte-ecowatt/assets/6975084/6912fc7c-57f5-41ec-b681-ee2d57f33705)
hello merci pour le repo ! j'ai tout implémenté mais je n'ai pas de data qui remonte.

J'ai loggué cette erreur :
```
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with RTE API: requests too frequent to RTE API

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 206, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Error communicating with RTE API: requests too frequent to RTE API
```

**Comment by kamaradclimber** [comment]
Bonjour,

l'erreur devrait être transitoire et disparaître en moins de 2h.  Est-elle toujours présente?

**Comment by dcyou** [comment]
ce matin toujours aucune data mais plus le message d'erreur effectivement.
<img width="337" alt="image" src="https://github.com/kamaradclimber/rte-ecowatt/assets/6975084/6552901e-7e07-446f-85ec-a064f5c891ee">
J'ai une erreur 
```
2023-08-13 17:13:58.434 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'               A@BAE@FAI   
```

mais je pense que cela est autre chose. J'inspecte + ce soir ou demain ;) merci
