### ISSUE TITLE
Exception depuis 0.7.0

### ISSUE THREAD

**Issue by Skuair** [kamaradclimber/rte-ecowatt#70]
Bonjour,

J'ai mis à jour vers la version 0.7.0 en suivant ce qui était préconisé à savoir suppression de l'intégration, réinstallation avec nouvelle clé API v5 puis ajout des sensors pour le lendemain et pour j+2.

Cependant, maintenant, les sensors ne sont pas tous peuplés, certains sont en état unknown et le logger remonte assez souvent l'erreur suivante :

```
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/rte_ecowatt/__init__.py:379
Integration: My EcoWatt by RTE (documentation, issues)
First occurred: 17:25:19 (15 occurrences)
Last logged: 21:09:19

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/rte_ecowatt/__init__.py", line 368, in _handle_coordinator_update
    self._state = self._level2string(ecowatt_level)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 379, in _level2string
    return {
           ^
KeyError: 0
```

Ci-dessous une capture des états des sensors dont certains sont unknown, sûrement à cause de l'erreur précédente :
![image](https://github.com/kamaradclimber/rte-ecowatt/assets/49756503/a9123124-98a5-40c2-a359-4f9b9ff9467d)

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/rte-ecowatt/releases/tag/0.7.2 devrait corriger le problème (je n'arrivais cependant pas à le reproduire)

**Comment by Skuair** [comment]
Merci, j'ai mis à jour ce matin, pas d'erreur depuis.
