### ISSUE TITLE
Erreurs lors de l'ajout du capteur délestage ENEDIS, semble bloquer le rafraichissement de tous les capteurs RTE

### ISSUE THREAD

**Issue by kalon33** [kamaradclimber/rte-ecowatt#75]
Bonjour,

Quand j'ajoute le capteur ecowatt par défaut, j'ai bien les valeurs qui remontent. Mais, dès que j'ajoute le capteur des délestages d'ENEDIS, je perds toute info dans le capteur Ecowatt et n'en ai aucune dans celui ENEDIS. Voici le log:

```
2023-11-28 21:34:44.379 DEBUG (MainThread) [custom_components.rte_ecowatt] Restoring state for enedis-electricity-distributor
2023-11-28 21:34:44.381 DEBUG (MainThread) [custom_components.rte_ecowatt] starting to restore sensor from previous data
2023-11-28 21:34:44.381 DEBUG (MainThread) [custom_components.rte_ecowatt] Restoring state for enedis-sent-address
2023-11-28 21:34:44.547 WARNING (MainThread) [custom_components.rte_ecowatt] Failure to fetch data from /shedding/state_js endpoint: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>

2023-11-28 21:34:44.548 DEBUG (MainThread) [custom_components.rte_ecowatt] Finished fetching enedis api data in 0.176 seconds (success: False)
2023-11-28 21:34:44.548 DEBUG (MainThread) [custom_components.rte_ecowatt] Last coordinator failed, assuming state has not changed
2023-11-28 21:34:44.548 DEBUG (MainThread) [custom_components.rte_ecowatt] Last coordinator failed, assuming state has not changed
2023-11-28 21:34:44.548 DEBUG (MainThread) [custom_components.rte_ecowatt] Last coordinator failed, assuming state has not changed
2023-11-28 21:34:44.548 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/rte_ecowatt/__init__.py", line 625, in update_method
    raise UpdateFailed("Failed fetching enedis data at step 1")
homeassistant.helpers.update_coordinator.UpdateFailed: Failed fetching enedis data at step 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 674, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Failed fetching enedis data at step 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 92, in async_setup_entry
    await enedis_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 262, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: Failed fetching enedis data at step 1
```

Merci d'avance pour le correctif !

**Comment by kamaradclimber** [comment]
Hello,

L’api d’Enedis semble avoir complètement disparue (après avoir été cachée derrière un captcha, cf https://github.com/kamaradclimber/rte-ecowatt/issues/63).
Je pense que je vais retirer le code sauf si une autre api existe.

**Comment by kalon33** [comment]
Enedis c'est quand même la plaie pour ce genre de choses...

**Comment by kamaradclimber** [comment]
Le site ecowatt est cassé apparemment car leur CDN est mort, heureusement l'api ecowatt est plus solide et fonctionne.
