### ISSUE TITLE
Init erreur

### ISSUE THREAD

**Issue by lahayeg** [kamaradclimber/rte-ecowatt#77]
Bonjour,

je viens d'installer via HACS, redémarrer et configuré

![Screenshot 2023-12-13 at 11 19 47](https://github.com/kamaradclimber/rte-ecowatt/assets/7801817/6172ab61-90f9-405e-87dd-a9b43d3b17ef)

Mais je vois les erreurs suivantes. Testé avec les params par defaut ainsi que 48 heures et 3 jours

```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.rte_ecowatt
Source: helpers/update_coordinator.py:300
Integration: My EcoWatt by RTE (documentation, issues)
First occurred: 11:11:28 (1 occurrences)
Last logged: 11:11:28

Unexpected error fetching ecowatt api data: the JSON object must be str, bytes or bytearray, not list
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 189, in update_method
    signals = json.loads(body)["signals"]
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
```
````
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Capteur (documentation, issues)
First occurred: 11:11:28 (1 occurrences)
Last logged: 11:11:28

Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rte_ecowatt/__init__.py", line 189, in update_method
    signals = json.loads(body)["signals"]
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rte_ecowatt/sensor.py", line 82, in async_setup_entry
    await rte_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: the JSON object must be str, bytes or bytearray, not list

```

**Comment by lahayeg** [comment]
l'integration semble ok finalement
![Screenshot 2023-12-13 at 15 21 41](https://github.com/kamaradclimber/rte-ecowatt/assets/7801817/185b3d1d-f89d-4d33-bb7b-a45de16989f9)
