### ISSUE TITLE
Warning in HA 2024.6

### ISSUE THREAD

**Issue by epenet** [kamaradclimber/rte-ecowatt#87]
**Describe the bug**
```
2024-06-06 17:55:16.337 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'rte_ecowatt' at custom_components/rte_ecowatt/__init__.py, line 404: return tz.gettz(timezone) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/kamaradclimber/rte-ecowatt/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/rte_ecowatt/__init__.py", line 62, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2032, in async_forward_entry_setups
await asyncio.gather(
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2034, in <genexpr>
create_eager_task(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup
await entry.async_setup(self.hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_setup_entry
return await component.async_setup_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry
return await self._platforms[key].async_setup_entry(config_entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry
return await self._async_setup_platform(async_create_setup_awaitable)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform
awaitable = create_eager_task(awaitable, loop=hass.loop)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/config/custom_components/rte_ecowatt/sensor.py", line 82, in async_setup_entry
await rte_coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh
await self._async_refresh(
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
update_callback()
File "/config/custom_components/rte_ecowatt/__init__.py", line 414, in _handle_coordinator_update
ecowatt_level = self._find_ecowatt_level()
File "/config/custom_components/rte_ecowatt/__init__.py", line 529, in _find_ecowatt_level
now = datetime.now(self._timezone())
File "/config/custom_components/rte_ecowatt/__init__.py", line 404, in _timezone
return tz.gettz(timezone)
```

** Versions **

HomeAssistant version: 2024.6
This integration version: 0.6.3

**Comment by epenet** [comment]
Offending code is:
https://github.com/kamaradclimber/rte-ecowatt/blob/1187c6c5f79152a4791b1f1360e690b978e7e314/custom_components/rte_ecowatt/__init__.py#L402-L404

**Comment by epenet** [comment]
Yes, it is probably easiest to simply use `dt_util.get_default_time_zone()`:

```python
    def _timezone(self) -> tzinfo:
        return dt_util.get_default_time_zone()
```

**Comment by kamaradclimber** [comment]
I won't have time to fix this warning in the near future (to be honest, I'm tired of HA developing team constantly deprecating items).

I would however welcome patches to fix this of course.
